### ISSUE TITLE
A error occured when get to home page. The mongodb query results is wrong.

### ISSUE THREAD

**Issue by charlie447** [charlie447/NodeBlog#1]
```
ReferenceError: result is not defined
    at Model.find (C:\project\NodeBlog\node_modules\_mongolass@4.1.0@mongolass\lib\query.js:101:16)
    at Object.getPosts (C:\project\NodeBlog\models\posts.js:41:10)
    at C:\project\NodeBlog\routes\posts.js:9:13
    at Layer.handle [as handle_request] (C:\project\NodeBlog\node_modules\_express@4.16.2@express\lib\router\layer.js:95:5)
    at next (C:\project\NodeBlog\node_modules\_express@4.16.2@express\lib\router\route.js:137:13)
    at Route.dispatch (C:\project\NodeBlog\node_modules\_express@4.16.2@express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\project\NodeBlog\node_modules\_express@4.16.2@express\lib\router\layer.js:95:5)
    at C:\project\NodeBlog\node_modules\_express@4.16.2@express\lib\router\index.js:281:22
    at Function.process_params (C:\project\NodeBlog\node_modules\_express@4.16.2@express\lib\router\index.js:335:12)
    at next (C:\project\NodeBlog\node_modules\_express@4.16.2@express\lib\router\index.js:275:10)
```
It seems need to set the `query` 's type change to MongoDB's ObjectId type.  Try it later.

**Comment by charlie447** [comment]
Reviewed the code, found the problem is at mongo.js, the Mongolass.plugin('addCreatedAt'...), there was a variable is wrong.
